package DeviceOnboarding;

public enum DeviceState {
    DEVICE_RECEIVED,
    SERIAL_NUMBER_RECORDED,
    DELIVERY_INFO_RECORDED,
    DAMAGE_RECORDED,
    SIM_INSERTED_AND_RECORDED,
    FLASHED,
    KEY_INJECTED,
    SENT_FOR_REPACK,
    STORED_IN_WAREHOUSE,
    SEVERE_FLASH_FAILURE,
    SEVERE_KEY_INJECTION_FAILURE,
    DEVICE_DAMAGED
}
